conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include

from .import views
from .forms import LoginForm

app_name= 'core'

urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns = [
    path("",views.index,name='index'),
]

ecomproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('',include('core.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path
from . import views

app_name='item'

urlpatterns =[
    path('',views.items,name='items'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.details,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit'),


]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':"Your username",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':"Your Password",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields =('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':"Your username",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':"Your email address ",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':"Your Password",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':"Repeat Password",
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category,Item
from .forms import SignupForm


def index(request):
    items= Item.objects.filter(is_sold=False)[0:6]
    categories =Category.objects.all()

    return render(request,'core/index.html',{
        'categories':categories,
        'items':items,
        
    })

def contact(request):
    return render(request,'core/contact.html')


def about(request):
    return render(request, "core/about.html")


def signup(request):

    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form =SignupForm()

    form = SignupForm()

    return render(request, 'core/signup.html',{
        'form' : form
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}
About
{% endblock %}


{% block content %}

<div>
    <span style="color: white;">
        <br>
    <h1 class="textalignment" >About<span style="color: red;"> US.</span></h1>
<i><p style="margin: 90px;">Welcome to CraftHome, where we are dedicated to preserving traditional crafts and cultural heritage. 
    Our mission is to celebrate the rich tapestry of diverse cultures by providing a platform for artisans and craftsmen to showcase their timeless creations. At CraftHome we believe that the essence of a community lies in its traditions, and we are committed to ensuring that these traditions endure and thrive.
     </p>
     <h3 class="textalignment">Our <span style="color: red;">vision</span></h3>
     <p style="margin: 90px;">We envision a world where traditional crafts and cultural heritage are not just preserved but also celebrated. Through our e-commerce platform, we aim to bridge the gap between artisans and enthusiasts, fostering a global community that appreciates and supports the beauty of handmade and culturally significant products.
     </p>
     <h3 class="textalignment">Our <span style="color: red;">Commitment</span></h3>
    <div class="main">
        <div class="abc">
            <h5><span style="color: red;">Preserving Heritage:</span></h5>
         <p>We are passionate about safeguarding traditional crafts that have been passed down through generations. By providing a marketplace for artisans, we contribute to the continuation of age-old techniques and skills.
        </p>
         </div>
         <div class="abc">
            <h5><span style="color: red;">Empowering Artisans:</span></h5>
            <p> Our platform is designed to empower artisans economically by connecting them directly with a global audience. We ensure fair compensation for their craftsmanship, fostering sustainable livelihoods.
            </p>
         </div>
         <div class="abc">
            <h5><span style="color: red;">Cultural Diversity:</span></h5>
            <p>CraftHome is a melting pot of cultures. We curate a diverse range of products, each telling a unique story and representing the rich heritage of different communities around the world.
            </p>
         </div>
    </div>
        <div class="main">
            <div class="abc">
                <h5><span style="color: red;">Quality and Authenticity: </span></h5>
                <P>We uphold the highest standards of quality and authenticity. Every product on our platform is carefully curated, ensuring that it not only reflects the cultural heritage but also meets the expectations of our discerning customers.
                </P></i>
             </div>
             <div class="abc">
                <h5><span style="color: red;">Handcrafted Treasures: </span></h5>
                <p>Handcrafted Treasures: Discover a curated collection of handcrafted items, each telling a story of tradition, skill, and passion. 
                </P></i>
             </div>
             <div class="abc">
                <h5><span style="color: red;">Cultural Artifacts: </span></h5>
                <P>Immerse yourself in the cultural heritage of various regions with our carefully selected artifacts that embody the spirit of their origins.
                </P></i>
             </div>
       </div>            

    <div  class="textalignment">
        <b><i>
            <P>Thank you for being a part of our mission to keep heritage alive.
            </P>
            <P>CraftHome Celebrating Tradition, Empowering Artisans.</P></span>
        </i></b>
    </div>

</div>

<style>
    body{
        font-size:x-large;
        font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        background-color: black;
        text-align: justify;
        width: 100%;
        height: 100vh;
        background-image: linear-gradient(rgba(0,0,0,0.75),rgba(0,0,0,0.75)),url(aboutus2.jpg);
        background-position: center;
        background-size: cover;
    }
    .textalignment{
        text-align: center;
        font-family: Georgia, 'Times New Roman', Times, serif;
        text-shadow: 10ch;
        margin: 20px;
    }
    h1{
        font-size: 80px;

    }
    .abc{
        width: 450px;
        text-align: center;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        line-height: 35px;
        margin: 10px solid black;
        box-shadow:  0px 5px 5px grey;
        border-radius: 15px;
        margin: 50px ;
        height: 430px;
        padding: 10px;
        transition: 0.3s;
    }
    .abc:hover{
        transform: scale(1.1);
    }
    p{
        text-align: center;
        line-height: 1.5cm;
    }
    .main{
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin: 20px;
        border-radius: 15px;
    }
    #navbar{
        background-color: white;
    }
</style>

{% endblock %}

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | CraftHome</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200" id="navbar">
            <a href="/" class="text-xl font-semibold"><h1 style="font-weight: bold; font-size: xx-large;">CRAFTHOME</h1>  </a>

            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <!-- <a href="/" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Log out</a> -->
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Thank you for being a part of our mission to keep heritage alive.

                    CraftHome Celebrating Tradition, Empowering Artisans.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
Contact
{% endblock %}


{% block content %}
<style>
    .banner{
        width: 100%;
        height: 100vh;
        background-image: linear-gradient(rgba(0,0,0,0.75),rgba(0,0,0,0.75)),url(cback.jpg);
        background-position: center;
        background-size: cover;
        background-attachment: fixed;
    }
    .align{
        position: absolute;
        top: 25%;
        text-align: center;
        transform: translateY(-50%);
        width: 100%;
        color: white;
        line-height: 12px;
        font-family:Georgia, 'Times New Roman', Times, serif;
    }
    h1{
        font-size: 80px;

    }
    .container {
        width: 1000px;
        margin: 0 auto;
        top: 25%;
        text-align: center;
        transform: translateY(100%);
        padding: 20px;
        border: 5px solid red;
        
        height: 320px;
        
        border-radius: 5px;
        background: linear-gradient(rgba(0,0,0,0.95),rgba(0,0,0,0.95));
        color: white;
        font-weight: bold;
    }
    .add,.pno,.email{
        width: 300px;
        text-align: center;
        font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
        line-height: 35px;
        margin: 10px solid black;
        box-shadow:  0px 5px 5px grey;
        border-radius: 15px;
        margin: 30px ;
        height: 140px;
    }
    .main{
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin: 20px;
        border-radius: 15px;
    }
    .pno div a{
        text-decoration: none;
        color: white;
    }
    .email div a{
        text-decoration: none;
        color: white;

    }
    .pno div a:hover{
        color: red;
    }
    .email div a:hover{
        color: red;
    }

</style>
<div class="banner">
    <div class="align">
        <h1>Contact <span style="color: red;">US.</span></h1>
    </div>
    <div class="container">
        <h1 class="h1" style="font-size: 50px;">Our Contact <span style="color: red;">Information</span></h1>
        <div class="main">
            <div class="add">
                <div ><span style="color: red;">Address</span></div>
                <div>Plot No-A2, Nirmalya Rd, near Golakhpuri Duplex, Patia, Bhubaneswar, Odisha 751024.</div>
            </div>
            <div class="pno">
                <div ><span style="color: red;">Phone</span></div>
            <div ><a href="#">+91 7873722984</a></div>
            </div>
            <div class="email">
                <div ><span style="color: red;">Email</span> </div>
                <div ><a href="#">support@thinkwebhub.com</a></div>
            </div>

        </div>
        
        
    </div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">

                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{item.price }}</p>
                    </div>
                </a>
            </div>

            

            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{ category.items.count }}items </p>
                    </div>
                </a>
            </div>


            {% endfor %}

        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Log in</h1>

        <form method="post" action=".">
            {% csrf_token %}
 
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password}}
         

            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {%for field in form %}
                {{ field.errors}}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock %}

{% block content %}

    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}
 
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat Password </label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {%for field in form %}
                {{ field.errors}}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>

{% endblock %}